/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  JSX,
} from '@stencil/core';
import {
  Link,
  MenuItems,
  Page,
  ReferenceKeys,
} from './definitions';
import {
  RouterHistory,
} from '@stencil/router';

export namespace Components {
  interface DocsButton {
    'href': string;
    'round': boolean;
  }
  interface DocsCode {
    'language': string;
  }
  interface DocsDemo {
    'source': string;
    'url': string;
  }
  interface DocsDropdown {
    'align': "left" | "right" | "center";
    'close': () => Promise<void>;
    'icon': (props: any) => JSX.Element;
    'label': string;
    'open': () => Promise<void>;
    'toggle': () => Promise<void>;
  }
  interface DocsHeader {
    'onToggleClick': (e: Event) => void;
  }
  interface DocsMenu {
    'onToggleClick': (e: Event) => void;
  }
  interface DocsMenuToggle {}
  interface DocsNav {
    'items': MenuItems;
  }
  interface DocsPage {
    'history': RouterHistory;
    'path': string;
  }
  interface DocsPageFooter {
    'page': Page;
  }
  interface DocsPagination {
    'page': Page;
  }
  interface DocsReference {
    'data': any[];
    'keys': ReferenceKeys;
  }
  interface DocsRoot {}
  interface DocsTab {
    'selected': boolean;
    'tab': string;
  }
  interface DocsTableOfContents {
    'basepath': string;
    'label': string;
    'links': Link[];
  }
  interface DocsTabs {
    'listenFor': string;
  }
  interface HeaderMobileCollapse {
    'darkMode': boolean;
  }
  interface IonicSearch {
    'mobile': boolean;
  }
}

declare global {


  interface HTMLDocsButtonElement extends Components.DocsButton, HTMLStencilElement {}
  var HTMLDocsButtonElement: {
    prototype: HTMLDocsButtonElement;
    new (): HTMLDocsButtonElement;
  };

  interface HTMLDocsCodeElement extends Components.DocsCode, HTMLStencilElement {}
  var HTMLDocsCodeElement: {
    prototype: HTMLDocsCodeElement;
    new (): HTMLDocsCodeElement;
  };

  interface HTMLDocsDemoElement extends Components.DocsDemo, HTMLStencilElement {}
  var HTMLDocsDemoElement: {
    prototype: HTMLDocsDemoElement;
    new (): HTMLDocsDemoElement;
  };

  interface HTMLDocsDropdownElement extends Components.DocsDropdown, HTMLStencilElement {}
  var HTMLDocsDropdownElement: {
    prototype: HTMLDocsDropdownElement;
    new (): HTMLDocsDropdownElement;
  };

  interface HTMLDocsHeaderElement extends Components.DocsHeader, HTMLStencilElement {}
  var HTMLDocsHeaderElement: {
    prototype: HTMLDocsHeaderElement;
    new (): HTMLDocsHeaderElement;
  };

  interface HTMLDocsMenuElement extends Components.DocsMenu, HTMLStencilElement {}
  var HTMLDocsMenuElement: {
    prototype: HTMLDocsMenuElement;
    new (): HTMLDocsMenuElement;
  };

  interface HTMLDocsMenuToggleElement extends Components.DocsMenuToggle, HTMLStencilElement {}
  var HTMLDocsMenuToggleElement: {
    prototype: HTMLDocsMenuToggleElement;
    new (): HTMLDocsMenuToggleElement;
  };

  interface HTMLDocsNavElement extends Components.DocsNav, HTMLStencilElement {}
  var HTMLDocsNavElement: {
    prototype: HTMLDocsNavElement;
    new (): HTMLDocsNavElement;
  };

  interface HTMLDocsPageElement extends Components.DocsPage, HTMLStencilElement {}
  var HTMLDocsPageElement: {
    prototype: HTMLDocsPageElement;
    new (): HTMLDocsPageElement;
  };

  interface HTMLDocsPageFooterElement extends Components.DocsPageFooter, HTMLStencilElement {}
  var HTMLDocsPageFooterElement: {
    prototype: HTMLDocsPageFooterElement;
    new (): HTMLDocsPageFooterElement;
  };

  interface HTMLDocsPaginationElement extends Components.DocsPagination, HTMLStencilElement {}
  var HTMLDocsPaginationElement: {
    prototype: HTMLDocsPaginationElement;
    new (): HTMLDocsPaginationElement;
  };

  interface HTMLDocsReferenceElement extends Components.DocsReference, HTMLStencilElement {}
  var HTMLDocsReferenceElement: {
    prototype: HTMLDocsReferenceElement;
    new (): HTMLDocsReferenceElement;
  };

  interface HTMLDocsRootElement extends Components.DocsRoot, HTMLStencilElement {}
  var HTMLDocsRootElement: {
    prototype: HTMLDocsRootElement;
    new (): HTMLDocsRootElement;
  };

  interface HTMLDocsTabElement extends Components.DocsTab, HTMLStencilElement {}
  var HTMLDocsTabElement: {
    prototype: HTMLDocsTabElement;
    new (): HTMLDocsTabElement;
  };

  interface HTMLDocsTableOfContentsElement extends Components.DocsTableOfContents, HTMLStencilElement {}
  var HTMLDocsTableOfContentsElement: {
    prototype: HTMLDocsTableOfContentsElement;
    new (): HTMLDocsTableOfContentsElement;
  };

  interface HTMLDocsTabsElement extends Components.DocsTabs, HTMLStencilElement {}
  var HTMLDocsTabsElement: {
    prototype: HTMLDocsTabsElement;
    new (): HTMLDocsTabsElement;
  };

  interface HTMLHeaderMobileCollapseElement extends Components.HeaderMobileCollapse, HTMLStencilElement {}
  var HTMLHeaderMobileCollapseElement: {
    prototype: HTMLHeaderMobileCollapseElement;
    new (): HTMLHeaderMobileCollapseElement;
  };

  interface HTMLIonicSearchElement extends Components.IonicSearch, HTMLStencilElement {}
  var HTMLIonicSearchElement: {
    prototype: HTMLIonicSearchElement;
    new (): HTMLIonicSearchElement;
  };
  interface HTMLElementTagNameMap {
    'docs-button': HTMLDocsButtonElement;
    'docs-code': HTMLDocsCodeElement;
    'docs-demo': HTMLDocsDemoElement;
    'docs-dropdown': HTMLDocsDropdownElement;
    'docs-header': HTMLDocsHeaderElement;
    'docs-menu': HTMLDocsMenuElement;
    'docs-menu-toggle': HTMLDocsMenuToggleElement;
    'docs-nav': HTMLDocsNavElement;
    'docs-page': HTMLDocsPageElement;
    'docs-page-footer': HTMLDocsPageFooterElement;
    'docs-pagination': HTMLDocsPaginationElement;
    'docs-reference': HTMLDocsReferenceElement;
    'docs-root': HTMLDocsRootElement;
    'docs-tab': HTMLDocsTabElement;
    'docs-table-of-contents': HTMLDocsTableOfContentsElement;
    'docs-tabs': HTMLDocsTabsElement;
    'header-mobile-collapse': HTMLHeaderMobileCollapseElement;
    'ionic-search': HTMLIonicSearchElement;
  }
}

declare namespace LocalJSX {
  interface DocsButton {
    'href'?: string;
    'round'?: boolean;
  }
  interface DocsCode {
    'language'?: string;
  }
  interface DocsDemo {
    'source'?: string;
    'url'?: string;
  }
  interface DocsDropdown {
    'align'?: "left" | "right" | "center";
    'icon'?: (props: any) => JSX.Element;
    'label'?: string;
  }
  interface DocsHeader {
    'onToggleClick'?: (e: Event) => void;
  }
  interface DocsMenu {
    'onToggleClick'?: (e: Event) => void;
  }
  interface DocsMenuToggle {}
  interface DocsNav {
    'items'?: MenuItems;
  }
  interface DocsPage {
    'history'?: RouterHistory;
    'path'?: string;
  }
  interface DocsPageFooter {
    'page'?: Page;
  }
  interface DocsPagination {
    'page'?: Page;
  }
  interface DocsReference {
    'data'?: any[];
    'keys'?: ReferenceKeys;
  }
  interface DocsRoot {}
  interface DocsTab {
    'selected'?: boolean;
    'tab'?: string;
  }
  interface DocsTableOfContents {
    'basepath'?: string;
    'label'?: string;
    'links'?: Link[];
  }
  interface DocsTabs {
    'listenFor'?: string;
  }
  interface HeaderMobileCollapse {
    'darkMode'?: boolean;
  }
  interface IonicSearch {
    'mobile'?: boolean;
  }

  interface IntrinsicElements {
    'docs-button': DocsButton;
    'docs-code': DocsCode;
    'docs-demo': DocsDemo;
    'docs-dropdown': DocsDropdown;
    'docs-header': DocsHeader;
    'docs-menu': DocsMenu;
    'docs-menu-toggle': DocsMenuToggle;
    'docs-nav': DocsNav;
    'docs-page': DocsPage;
    'docs-page-footer': DocsPageFooter;
    'docs-pagination': DocsPagination;
    'docs-reference': DocsReference;
    'docs-root': DocsRoot;
    'docs-tab': DocsTab;
    'docs-table-of-contents': DocsTableOfContents;
    'docs-tabs': DocsTabs;
    'header-mobile-collapse': HeaderMobileCollapse;
    'ionic-search': IonicSearch;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'docs-button': LocalJSX.DocsButton & JSXBase.HTMLAttributes<HTMLDocsButtonElement>;
      'docs-code': LocalJSX.DocsCode & JSXBase.HTMLAttributes<HTMLDocsCodeElement>;
      'docs-demo': LocalJSX.DocsDemo & JSXBase.HTMLAttributes<HTMLDocsDemoElement>;
      'docs-dropdown': LocalJSX.DocsDropdown & JSXBase.HTMLAttributes<HTMLDocsDropdownElement>;
      'docs-header': LocalJSX.DocsHeader & JSXBase.HTMLAttributes<HTMLDocsHeaderElement>;
      'docs-menu': LocalJSX.DocsMenu & JSXBase.HTMLAttributes<HTMLDocsMenuElement>;
      'docs-menu-toggle': LocalJSX.DocsMenuToggle & JSXBase.HTMLAttributes<HTMLDocsMenuToggleElement>;
      'docs-nav': LocalJSX.DocsNav & JSXBase.HTMLAttributes<HTMLDocsNavElement>;
      'docs-page': LocalJSX.DocsPage & JSXBase.HTMLAttributes<HTMLDocsPageElement>;
      'docs-page-footer': LocalJSX.DocsPageFooter & JSXBase.HTMLAttributes<HTMLDocsPageFooterElement>;
      'docs-pagination': LocalJSX.DocsPagination & JSXBase.HTMLAttributes<HTMLDocsPaginationElement>;
      'docs-reference': LocalJSX.DocsReference & JSXBase.HTMLAttributes<HTMLDocsReferenceElement>;
      'docs-root': LocalJSX.DocsRoot & JSXBase.HTMLAttributes<HTMLDocsRootElement>;
      'docs-tab': LocalJSX.DocsTab & JSXBase.HTMLAttributes<HTMLDocsTabElement>;
      'docs-table-of-contents': LocalJSX.DocsTableOfContents & JSXBase.HTMLAttributes<HTMLDocsTableOfContentsElement>;
      'docs-tabs': LocalJSX.DocsTabs & JSXBase.HTMLAttributes<HTMLDocsTabsElement>;
      'header-mobile-collapse': LocalJSX.HeaderMobileCollapse & JSXBase.HTMLAttributes<HTMLHeaderMobileCollapseElement>;
      'ionic-search': LocalJSX.IonicSearch & JSXBase.HTMLAttributes<HTMLIonicSearchElement>;
    }
  }
}


