/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  ValidationRule,
} from './components/input/input';

export namespace Components {
  interface ClioButton {
    /**
    * This property defines the priority or role of a button.
    */
    'buttonStyle'?: "primary" | "secondary" | "danger";
    /**
    * If true, the user cannot interact with the button.
    */
    'disabled'?: boolean;
    /**
    * The link that the user would like the button to lead to
    */
    'href'?: string;
    /**
    * If true, renders a loading state and the user cannot interact with the button.
    */
    'loading'?: boolean;
    /**
    * The relationship between the current document and the linked document
    */
    'rel'?: "noopener" | "noreferrer";
    /**
    * Defines the two available size formats for buttons. Set to `small` where space is at a premium, such as in a data table.
    */
    'size'?: "default" | "small";
    /**
    * The specified target that the link will open in
    */
    'target'?: "_blank" | "_self" | "_parent" | "_top" | "framename";
    /**
    * The type of the button.
    */
    'type'?: "submit" | "reset" | "button";
  }
  interface ClioCheckbox {
    /**
    * The ID of the element that describes the checkbox.
    */
    'ariaDescribedby'?: string;
    /**
    * If no visible label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If a custom label element is being used, set this to the `id` of that label element to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * If true, the checkbox is checked.
    */
    'checked': boolean;
    /**
    * If true, the checkbox cannot be interacted with.
    */
    'disabled'?: boolean;
    /**
    * If true, the checkbox will visually appear as indeterminate.
    */
    'indeterminate'?: boolean;
    /**
    * Returns the validity state of the checkbox.
    * @returns
    */
    'isValid': () => Promise<boolean>;
    /**
    * The label for the checkbox.
    */
    'label'?: string;
    /**
    * The name of the control, which is submitted with the form data.
    */
    'name': string;
    /**
    * If true, the checkbox is required.
    */
    'required'?: boolean;
    /**
    * Forces the checkbox to validate.
    * @returns
    */
    'validate': () => Promise<void>;
    /**
    * The value of the toggle does not mean if it's checked or not, use the `checked` property for that.  The value of a toggle is analogous to the value of a `<input type="checkbox">`, it's only used when the toggle participates in a native `<form>`. Defaults to "on".
    */
    'value'?: string | number;
  }
  interface ClioComboButton {
    /**
    * This property defines the priority or role of a button.
    */
    'buttonStyle'?: "primary" | "secondary" | "danger";
    /**
    * The function that will handle the click event of the primary action button.
    */
    'primaryActionClick': Function;
    /**
    * The text that will appear in the primary button.
    */
    'primaryActionLabel': string;
    /**
    * Defines the two available size formats for combo-buttons. Set to small where space is at a premium, such as in a data table.
    */
    'size'?: "default" | "small";
  }
  interface ClioForm {
    /**
    * The URI of a program that processes the form information.
    */
    'action'?: string;
    /**
    * If true, form won't be submitted through an AJAX request and will redirect to the action URL after the form has been submitted.
    */
    'allowRedirect'?: boolean;
    /**
    * The id of the element which describes the form.
    */
    'ariaDescribedby'?: string;
    /**
    * Labels the form for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * The id of the element that labels the form.
    */
    'ariaLabelledby'?: string;
    /**
    * Indicates whether input elements can by default have their values automatically completed by the browser.
    */
    'autocomplete'?: "on" | "off";
    /**
    * When the value of the method attribute is post, enctype is the MIME type of content that is used to submit the form to the server.
    */
    'enctype'?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain";
    /**
    * Returns true if the form contains dirty inputs.
    * @returns
    */
    'isDirty': () => Promise<boolean>;
    /**
    * Returns true if the form is valid.
    * @returns
    */
    'isValid': () => Promise<boolean>;
    /**
    * The HTTP method that the browser uses to submit the form.
    */
    'method'?: "post" | "get" | "dialog";
    /**
    * The name of the form.
    */
    'name'?: string;
    /**
    * This indicates that the form is not to be validated when submitted.
    */
    'novalidate'?: boolean;
    /**
    * Submit the form.
    * @returns
    */
    'submit': () => Promise<void>;
    /**
    * A name or keyword indicating where to display the response that is received after submitting the form.
    */
    'target'?: "_self" | "_blank" | "_parent" | "_top" | string;
    /**
    * Forces the form to validate. It calls triggerValidationChecks() which calls the .validate() method on each input
    * @returns
    */
    'validate': () => Promise<void>;
  }
  interface ClioFormError {
    /**
    * A custom error message. Use this to override HTML5 validation message.
    */
    'message'?: string;
  }
  interface ClioIcon {
    /**
    * Used this to provide context for screen readers. Defaults to the icon name.
    */
    'ariaLabel'?: string;
    /**
    * The color for the icon. Accepts hexidecimal, rgb(a), hsl(a), and string values.
    */
    'color'?: string;
    /**
    * The name of the icon to render.
    */
    'name': "caret-down" | "checkbox" | "dash" | "error";
  }
  interface ClioInput {
    /**
    * If a custom sub-label element is being used, set this to the `id` of that sub-label element to provide context for screen readers.
    */
    'ariaDescribedby'?: string;
    /**
    * If no visible label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If a custom label element is being used, set this to the `id` of that label element to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * Indicates whether the value of the control can be automatically completed by the browser.
    */
    'autocomplete': "off" | "on";
    /**
    * Specify that a form control should have input focus when the page loads.
    */
    'autofocus': boolean;
    /**
    * If true the input field cannot be interacted with.
    */
    'disabled': boolean;
    /**
    * A method that returns the input's icon element.
    */
    'getIconElement': () => Promise<HTMLElement>;
    /**
    * Specifies the icon that is to be associated with the input.
    */
    'icon'?: "caret-down" | "checkbox" | "dash" | "error";
    /**
    * Returns the dirty state of the input.
    * @returns
    */
    'isDirty': () => Promise<boolean>;
    /**
    * Returns the validity state of the input.
    * @returns
    */
    'isValid': () => Promise<boolean>;
    /**
    * The label for the input.
    */
    'label'?: string;
    /**
    * If true the input field will show a loading icon.
    */
    'loading': boolean;
    /**
    * The name of the input, which is submitted with the form data.
    */
    'name': string;
    /**
    * Instructional text that shows before the input has a value.
    */
    'placeholder': string;
    /**
    * If true the input field is required.
    */
    'required': boolean;
    /**
    * Manually sets the dirty state of the input.
    */
    'setDirty': (dirty: boolean) => Promise<void>;
    /**
    * Sets focus on the specified `clio-input`. Use this method instead of the global `input.focus()`.
    */
    'setFocus': () => Promise<void>;
    /**
    * The sub-label for the input.
    */
    'subLabel'?: string;
    /**
    * Provides additional context to the user, (ex. “$” or “$/hr”).
    */
    'suffix'?: string;
    /**
    * The type of input field to display.
    */
    'type': "date" | "email" | "number" | "password" | "search" | "tel" | "text" | "time" | "url";
    /**
    * Forces the input to validate. It calls handleValidity() and passes an optional `force` boolean.
    * @returns
    */
    'validate': () => Promise<void>;
    /**
    * An array of validation rules can be passed in to provide validation checking.
    */
    'validationRules': ValidationRule[];
    /**
    * Specifies the value of the element
    */
    'value': string;
  }
  interface ClioLabel {
    /**
    * The id value of the input that the label is associated with.
    */
    'for'?: string;
    /**
    * The type of label. Allows a label to use the required or sub-label styling.
    */
    'labelType': "required" | "sub-label" | "default";
  }
  interface ClioLoader {
    /**
    * Labels the form for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * Sets the loader to "default" or "reversed" style.
    */
    'loaderStyle'?: "reversed" | "default";
    /**
    * Sets the size of Sets the size of the loader.
    */
    'size'?: "small" | "large";
  }
  interface ClioMenu {}
  interface ClioMenuItem {
    /**
    * If true, the user cannot interact with the menu item.
    */
    'disabled'?: boolean;
    /**
    * The link that the user would like the menu-item to lead to.
    */
    'href'?: string;
  }
  interface ClioPill {
    /**
    * Sets the background color and corresponding text color of the pill.
    */
    'color': "green" | "yellow" | "orange" | "red" | "teal" | "grey";
  }
  interface ClioPopover {
    /**
    * This is the element that should control the popover's active state and which the popover is position relative to. Ex. a `<clio-button>`
    */
    'activator': HTMLElement;
    /**
    * This determines whether the popover is visible or not.
    */
    'active'?: boolean;
    /**
    * This determines the horizontal alignment of the popover relative to its activator.
    */
    'alignX'?: "left" | "middle" | "right";
    /**
    * This determines the vertical alignment of the popover relative to its activator.
    */
    'alignY'?: "bottom" | "middle" | "top";
    /**
    * This determines whether the popover should attempt to automatically find and focus on content. Defaults to `true`.
    */
    'autofocus'?: boolean;
    /**
    * This determines how much padding is applied to the popover content container.
    */
    'padding'?: "none" | "xs" | "s" | "m" | "l" | "xl";
    /**
    * The role of the popover.
    */
    'role'?: string;
  }
  interface ClioRadio {
    /**
    * If a custom sub-label element is being used, set this to the `id` of that sub-label element to provide context for screen readers.
    */
    'ariaDescribedby'?: string;
    /**
    * If no visible label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If a custom label element is being used, set this to the `id` of that label element to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * If true, radio cannot be interacted with.
    */
    'disabled'?: boolean;
    /**
    * The label for the radio.
    */
    'label'?: string;
    /**
    * The name of the control, which is submitted with the form data.
    */
    'name': string;
    /**
    * The value of the radio.
    */
    'value': any;
  }
  interface ClioRadioGroup {
    /**
    * The label for the radio group.
    */
    'label'?: string;
    /**
    * The name of the radio group, which is submitted with the form data.
    */
    'name': string;
    /**
    * The value of the radio group.
    */
    'value'?: any;
  }
  interface ClioSelect {
    /**
    * If a custom sub-label element is being used, set this to the `id` of that sub-label element to provide context for screen readers.
    */
    'ariaDescribedby'?: string;
    /**
    * If no visible label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If a custom label element is being used, set this to the `id` of that label element to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * Sets whether this element will receive focus when it is rendered.
    */
    'autofocus': boolean;
    /**
    * Returns the dirty state of the select.
    * @returns
    */
    'isDirty': () => Promise<boolean>;
    /**
    * Returns the validity state of the select.
    * @returns
    */
    'isValid': () => Promise<boolean>;
    /**
    * The items that will be displayed as `<clio-menu-item>`s within a `<clio-popover>`.
    */
    'items': Array<{ label: string; value: number | string }>;
    /**
    * The label for the input.
    */
    'label'?: string;
    /**
    * If true, a loading spinner is displayed within the text input.
    */
    'loading': boolean;
    /**
    * The name of the control, which is submitted with the form data.
    */
    'name': string;
    /**
    * If true, this field is required.
    */
    'required'?: boolean;
    /**
    * Manually sets the dirty state of the select.
    */
    'setDirty': (dirty: boolean) => Promise<void>;
    /**
    * Sets focus on the input element.
    */
    'setFocus': () => Promise<void>;
    /**
    * The sub-label for the input.
    */
    'subLabel'?: string;
    /**
    * Forces the select to validate. It calls the Input's validate() method.
    * @returns
    */
    'validate': () => Promise<void>;
    /**
    * The value of the item that is currently selected. This can be used to set an initial value as well.
    */
    'value'?: number | string;
  }
  interface ClioTextarea {
    /**
    * If no sub-label is provided, use this to provide context for screen readers.
    */
    'ariaDescribedby'?: string;
    /**
    * If no label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If no label is provided, use this to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * Specify that a form control should give the textarea focus when the page loads.
    */
    'autofocus'?: boolean;
    /**
    * If true, the textarea will be disabled.
    */
    'disabled'?: boolean;
    /**
    * Returns the dirty state of the textarea.
    * @returns
    */
    'isDirty': () => Promise<boolean>;
    /**
    * Returns the validity state of the textarea.
    * @returns
    */
    'isValid': () => Promise<boolean>;
    /**
    * The label for the input.
    */
    'label'?: string;
    /**
    * The name of the textarea, which is submitted with the form data.
    */
    'name': string;
    /**
    * Instructional text that shows before the textarea has a value.
    */
    'placeholder'?: string;
    /**
    * If true, the textarea is required.
    */
    'required'?: boolean;
    /**
    * Manually sets the dirty state of the textarea.
    */
    'setDirty': (dirty: boolean) => Promise<void>;
    /**
    * Sets focus on the specified `clio-textarea`. Use this method instead of the global `textarea.focus()`.
    */
    'setFocus': () => Promise<void>;
    /**
    * The sub-label for the input.
    */
    'subLabel'?: string;
    /**
    * Forces the textarea to validate. Returns `true` if the textarea is valid.
    * @returns
    */
    'validate': () => Promise<boolean>;
    /**
    * Specifies the value of the element.
    */
    'value'?: string;
  }
  interface NovaExample {
    /**
    * This property sets a title label for the example
    */
    'label': string;
  }
}

declare global {


  interface HTMLClioButtonElement extends Components.ClioButton, HTMLStencilElement {}
  var HTMLClioButtonElement: {
    prototype: HTMLClioButtonElement;
    new (): HTMLClioButtonElement;
  };

  interface HTMLClioCheckboxElement extends Components.ClioCheckbox, HTMLStencilElement {}
  var HTMLClioCheckboxElement: {
    prototype: HTMLClioCheckboxElement;
    new (): HTMLClioCheckboxElement;
  };

  interface HTMLClioComboButtonElement extends Components.ClioComboButton, HTMLStencilElement {}
  var HTMLClioComboButtonElement: {
    prototype: HTMLClioComboButtonElement;
    new (): HTMLClioComboButtonElement;
  };

  interface HTMLClioFormElement extends Components.ClioForm, HTMLStencilElement {}
  var HTMLClioFormElement: {
    prototype: HTMLClioFormElement;
    new (): HTMLClioFormElement;
  };

  interface HTMLClioFormErrorElement extends Components.ClioFormError, HTMLStencilElement {}
  var HTMLClioFormErrorElement: {
    prototype: HTMLClioFormErrorElement;
    new (): HTMLClioFormErrorElement;
  };

  interface HTMLClioIconElement extends Components.ClioIcon, HTMLStencilElement {}
  var HTMLClioIconElement: {
    prototype: HTMLClioIconElement;
    new (): HTMLClioIconElement;
  };

  interface HTMLClioInputElement extends Components.ClioInput, HTMLStencilElement {}
  var HTMLClioInputElement: {
    prototype: HTMLClioInputElement;
    new (): HTMLClioInputElement;
  };

  interface HTMLClioLabelElement extends Components.ClioLabel, HTMLStencilElement {}
  var HTMLClioLabelElement: {
    prototype: HTMLClioLabelElement;
    new (): HTMLClioLabelElement;
  };

  interface HTMLClioLoaderElement extends Components.ClioLoader, HTMLStencilElement {}
  var HTMLClioLoaderElement: {
    prototype: HTMLClioLoaderElement;
    new (): HTMLClioLoaderElement;
  };

  interface HTMLClioMenuElement extends Components.ClioMenu, HTMLStencilElement {}
  var HTMLClioMenuElement: {
    prototype: HTMLClioMenuElement;
    new (): HTMLClioMenuElement;
  };

  interface HTMLClioMenuItemElement extends Components.ClioMenuItem, HTMLStencilElement {}
  var HTMLClioMenuItemElement: {
    prototype: HTMLClioMenuItemElement;
    new (): HTMLClioMenuItemElement;
  };

  interface HTMLClioPillElement extends Components.ClioPill, HTMLStencilElement {}
  var HTMLClioPillElement: {
    prototype: HTMLClioPillElement;
    new (): HTMLClioPillElement;
  };

  interface HTMLClioPopoverElement extends Components.ClioPopover, HTMLStencilElement {}
  var HTMLClioPopoverElement: {
    prototype: HTMLClioPopoverElement;
    new (): HTMLClioPopoverElement;
  };

  interface HTMLClioRadioElement extends Components.ClioRadio, HTMLStencilElement {}
  var HTMLClioRadioElement: {
    prototype: HTMLClioRadioElement;
    new (): HTMLClioRadioElement;
  };

  interface HTMLClioRadioGroupElement extends Components.ClioRadioGroup, HTMLStencilElement {}
  var HTMLClioRadioGroupElement: {
    prototype: HTMLClioRadioGroupElement;
    new (): HTMLClioRadioGroupElement;
  };

  interface HTMLClioSelectElement extends Components.ClioSelect, HTMLStencilElement {}
  var HTMLClioSelectElement: {
    prototype: HTMLClioSelectElement;
    new (): HTMLClioSelectElement;
  };

  interface HTMLClioTextareaElement extends Components.ClioTextarea, HTMLStencilElement {}
  var HTMLClioTextareaElement: {
    prototype: HTMLClioTextareaElement;
    new (): HTMLClioTextareaElement;
  };

  interface HTMLNovaExampleElement extends Components.NovaExample, HTMLStencilElement {}
  var HTMLNovaExampleElement: {
    prototype: HTMLNovaExampleElement;
    new (): HTMLNovaExampleElement;
  };
  interface HTMLElementTagNameMap {
    'clio-button': HTMLClioButtonElement;
    'clio-checkbox': HTMLClioCheckboxElement;
    'clio-combo-button': HTMLClioComboButtonElement;
    'clio-form': HTMLClioFormElement;
    'clio-form-error': HTMLClioFormErrorElement;
    'clio-icon': HTMLClioIconElement;
    'clio-input': HTMLClioInputElement;
    'clio-label': HTMLClioLabelElement;
    'clio-loader': HTMLClioLoaderElement;
    'clio-menu': HTMLClioMenuElement;
    'clio-menu-item': HTMLClioMenuItemElement;
    'clio-pill': HTMLClioPillElement;
    'clio-popover': HTMLClioPopoverElement;
    'clio-radio': HTMLClioRadioElement;
    'clio-radio-group': HTMLClioRadioGroupElement;
    'clio-select': HTMLClioSelectElement;
    'clio-textarea': HTMLClioTextareaElement;
    'nova-example': HTMLNovaExampleElement;
  }
}

declare namespace LocalJSX {
  interface ClioButton {
    /**
    * This property defines the priority or role of a button.
    */
    'buttonStyle'?: "primary" | "secondary" | "danger";
    /**
    * If true, the user cannot interact with the button.
    */
    'disabled'?: boolean;
    /**
    * The link that the user would like the button to lead to
    */
    'href'?: string;
    /**
    * If true, renders a loading state and the user cannot interact with the button.
    */
    'loading'?: boolean;
    /**
    * Emitted when the button loses focus.
    */
    'onClioBlur'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the button has focus.
    */
    'onClioFocus'?: (event: CustomEvent<void>) => void;
    /**
    * The relationship between the current document and the linked document
    */
    'rel'?: "noopener" | "noreferrer";
    /**
    * Defines the two available size formats for buttons. Set to `small` where space is at a premium, such as in a data table.
    */
    'size'?: "default" | "small";
    /**
    * The specified target that the link will open in
    */
    'target'?: "_blank" | "_self" | "_parent" | "_top" | "framename";
    /**
    * The type of the button.
    */
    'type'?: "submit" | "reset" | "button";
  }
  interface ClioCheckbox {
    /**
    * The ID of the element that describes the checkbox.
    */
    'ariaDescribedby'?: string;
    /**
    * If no visible label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If a custom label element is being used, set this to the `id` of that label element to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * If true, the checkbox is checked.
    */
    'checked'?: boolean;
    /**
    * If true, the checkbox cannot be interacted with.
    */
    'disabled'?: boolean;
    /**
    * If true, the checkbox will visually appear as indeterminate.
    */
    'indeterminate'?: boolean;
    /**
    * The label for the checkbox.
    */
    'label'?: string;
    /**
    * The name of the control, which is submitted with the form data.
    */
    'name'?: string;
    /**
    * Emitted when `checked` value changes.
    */
    'onClioChange'?: (event: CustomEvent<{ checked: boolean }>) => void;
    /**
    * If true, the checkbox is required.
    */
    'required'?: boolean;
    /**
    * The value of the toggle does not mean if it's checked or not, use the `checked` property for that.  The value of a toggle is analogous to the value of a `<input type="checkbox">`, it's only used when the toggle participates in a native `<form>`. Defaults to "on".
    */
    'value'?: string | number;
  }
  interface ClioComboButton {
    /**
    * This property defines the priority or role of a button.
    */
    'buttonStyle'?: "primary" | "secondary" | "danger";
    /**
    * The function that will handle the click event of the primary action button.
    */
    'primaryActionClick'?: Function;
    /**
    * The text that will appear in the primary button.
    */
    'primaryActionLabel'?: string;
    /**
    * Defines the two available size formats for combo-buttons. Set to small where space is at a premium, such as in a data table.
    */
    'size'?: "default" | "small";
  }
  interface ClioForm {
    /**
    * The URI of a program that processes the form information.
    */
    'action'?: string;
    /**
    * If true, form won't be submitted through an AJAX request and will redirect to the action URL after the form has been submitted.
    */
    'allowRedirect'?: boolean;
    /**
    * The id of the element which describes the form.
    */
    'ariaDescribedby'?: string;
    /**
    * Labels the form for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * The id of the element that labels the form.
    */
    'ariaLabelledby'?: string;
    /**
    * Indicates whether input elements can by default have their values automatically completed by the browser.
    */
    'autocomplete'?: "on" | "off";
    /**
    * When the value of the method attribute is post, enctype is the MIME type of content that is used to submit the form to the server.
    */
    'enctype'?: "application/x-www-form-urlencoded" | "multipart/form-data" | "text/plain";
    /**
    * The HTTP method that the browser uses to submit the form.
    */
    'method'?: "post" | "get" | "dialog";
    /**
    * The name of the form.
    */
    'name'?: string;
    /**
    * This indicates that the form is not to be validated when submitted.
    */
    'novalidate'?: boolean;
    /**
    * Emitted when the form has been submitted.
    */
    'onClioSubmit'?: (event: CustomEvent<any>) => void;
    /**
    * A name or keyword indicating where to display the response that is received after submitting the form.
    */
    'target'?: "_self" | "_blank" | "_parent" | "_top" | string;
  }
  interface ClioFormError {
    /**
    * A custom error message. Use this to override HTML5 validation message.
    */
    'message'?: string;
  }
  interface ClioIcon {
    /**
    * Used this to provide context for screen readers. Defaults to the icon name.
    */
    'ariaLabel'?: string;
    /**
    * The color for the icon. Accepts hexidecimal, rgb(a), hsl(a), and string values.
    */
    'color'?: string;
    /**
    * The name of the icon to render.
    */
    'name': "caret-down" | "checkbox" | "dash" | "error";
  }
  interface ClioInput {
    /**
    * If a custom sub-label element is being used, set this to the `id` of that sub-label element to provide context for screen readers.
    */
    'ariaDescribedby'?: string;
    /**
    * If no visible label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If a custom label element is being used, set this to the `id` of that label element to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * Indicates whether the value of the control can be automatically completed by the browser.
    */
    'autocomplete'?: "off" | "on";
    /**
    * Specify that a form control should have input focus when the page loads.
    */
    'autofocus'?: boolean;
    /**
    * If true the input field cannot be interacted with.
    */
    'disabled'?: boolean;
    /**
    * Specifies the icon that is to be associated with the input.
    */
    'icon'?: "caret-down" | "checkbox" | "dash" | "error";
    /**
    * The label for the input.
    */
    'label'?: string;
    /**
    * If true the input field will show a loading icon.
    */
    'loading'?: boolean;
    /**
    * The name of the input, which is submitted with the form data.
    */
    'name': string;
    /**
    * Emitted when the input loses focus.
    */
    'onClioBlur'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the enter key is pressed.
    */
    'onClioInputEnterKeyPress'?: (event: CustomEvent<any>) => void;
    /**
    * Instructional text that shows before the input has a value.
    */
    'placeholder'?: string;
    /**
    * If true the input field is required.
    */
    'required'?: boolean;
    /**
    * The sub-label for the input.
    */
    'subLabel'?: string;
    /**
    * Provides additional context to the user, (ex. “$” or “$/hr”).
    */
    'suffix'?: string;
    /**
    * The type of input field to display.
    */
    'type'?: "date" | "email" | "number" | "password" | "search" | "tel" | "text" | "time" | "url";
    /**
    * An array of validation rules can be passed in to provide validation checking.
    */
    'validationRules'?: ValidationRule[];
    /**
    * Specifies the value of the element
    */
    'value'?: string;
  }
  interface ClioLabel {
    /**
    * The id value of the input that the label is associated with.
    */
    'for'?: string;
    /**
    * The type of label. Allows a label to use the required or sub-label styling.
    */
    'labelType'?: "required" | "sub-label" | "default";
  }
  interface ClioLoader {
    /**
    * Labels the form for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * Sets the loader to "default" or "reversed" style.
    */
    'loaderStyle'?: "reversed" | "default";
    /**
    * Sets the size of Sets the size of the loader.
    */
    'size'?: "small" | "large";
  }
  interface ClioMenu {}
  interface ClioMenuItem {
    /**
    * If true, the user cannot interact with the menu item.
    */
    'disabled'?: boolean;
    /**
    * The link that the user would like the menu-item to lead to.
    */
    'href'?: string;
    /**
    * Emitted when the menu item is activated by a click or keydown event.
    */
    'onClioMenuItemActivated'?: (event: CustomEvent<any>) => void;
    /**
    * Emitted when the menu item is hovered by a mouse.
    */
    'onClioMenuItemHovered'?: (event: CustomEvent<any>) => void;
  }
  interface ClioPill {
    /**
    * Sets the background color and corresponding text color of the pill.
    */
    'color'?: "green" | "yellow" | "orange" | "red" | "teal" | "grey";
  }
  interface ClioPopover {
    /**
    * This is the element that should control the popover's active state and which the popover is position relative to. Ex. a `<clio-button>`
    */
    'activator': HTMLElement;
    /**
    * This determines whether the popover is visible or not.
    */
    'active'?: boolean;
    /**
    * This determines the horizontal alignment of the popover relative to its activator.
    */
    'alignX'?: "left" | "middle" | "right";
    /**
    * This determines the vertical alignment of the popover relative to its activator.
    */
    'alignY'?: "bottom" | "middle" | "top";
    /**
    * This determines whether the popover should attempt to automatically find and focus on content. Defaults to `true`.
    */
    'autofocus'?: boolean;
    /**
    * Emitted when the popover visisbility is toggled.
    */
    'onClioPopoverVisibilityToggled'?: (event: CustomEvent<any>) => void;
    /**
    * This determines how much padding is applied to the popover content container.
    */
    'padding'?: "none" | "xs" | "s" | "m" | "l" | "xl";
    /**
    * The role of the popover.
    */
    'role'?: string;
  }
  interface ClioRadio {
    /**
    * If a custom sub-label element is being used, set this to the `id` of that sub-label element to provide context for screen readers.
    */
    'ariaDescribedby'?: string;
    /**
    * If no visible label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If a custom label element is being used, set this to the `id` of that label element to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * If true, radio cannot be interacted with.
    */
    'disabled'?: boolean;
    /**
    * The label for the radio.
    */
    'label'?: string;
    /**
    * The name of the control, which is submitted with the form data.
    */
    'name'?: string;
    /**
    * The value of the radio.
    */
    'value'?: any;
  }
  interface ClioRadioGroup {
    /**
    * The label for the radio group.
    */
    'label'?: string;
    /**
    * The name of the radio group, which is submitted with the form data.
    */
    'name'?: string;
    /**
    * Emitted when the value has changed.
    */
    'onClioChange'?: (event: CustomEvent<{ value: string }>) => void;
    /**
    * The value of the radio group.
    */
    'value'?: any;
  }
  interface ClioSelect {
    /**
    * If a custom sub-label element is being used, set this to the `id` of that sub-label element to provide context for screen readers.
    */
    'ariaDescribedby'?: string;
    /**
    * If no visible label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If a custom label element is being used, set this to the `id` of that label element to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * Sets whether this element will receive focus when it is rendered.
    */
    'autofocus'?: boolean;
    /**
    * The items that will be displayed as `<clio-menu-item>`s within a `<clio-popover>`.
    */
    'items'?: Array<{ label: string; value: number | string }>;
    /**
    * The label for the input.
    */
    'label'?: string;
    /**
    * If true, a loading spinner is displayed within the text input.
    */
    'loading'?: boolean;
    /**
    * The name of the control, which is submitted with the form data.
    */
    'name'?: string;
    /**
    * Emitted when `clio-input` value changes.
    */
    'onClioInput'?: (event: CustomEvent<{ value: string }>) => void;
    /**
    * Emitted when the selected value changes.
    */
    'onClioItemSelected'?: (event: CustomEvent<{ label: string; value: number | string }>) => void;
    /**
    * If true, this field is required.
    */
    'required'?: boolean;
    /**
    * The sub-label for the input.
    */
    'subLabel'?: string;
    /**
    * The value of the item that is currently selected. This can be used to set an initial value as well.
    */
    'value'?: number | string;
  }
  interface ClioTextarea {
    /**
    * If no sub-label is provided, use this to provide context for screen readers.
    */
    'ariaDescribedby'?: string;
    /**
    * If no label is provided, use this to provide context for screen readers.
    */
    'ariaLabel'?: string;
    /**
    * If no label is provided, use this to provide context for screen readers.
    */
    'ariaLabelledby'?: string;
    /**
    * Specify that a form control should give the textarea focus when the page loads.
    */
    'autofocus'?: boolean;
    /**
    * If true, the textarea will be disabled.
    */
    'disabled'?: boolean;
    /**
    * The label for the input.
    */
    'label'?: string;
    /**
    * The name of the textarea, which is submitted with the form data.
    */
    'name': string;
    /**
    * Instructional text that shows before the textarea has a value.
    */
    'placeholder'?: string;
    /**
    * If true, the textarea is required.
    */
    'required'?: boolean;
    /**
    * The sub-label for the input.
    */
    'subLabel'?: string;
    /**
    * Specifies the value of the element.
    */
    'value'?: string;
  }
  interface NovaExample {
    /**
    * This property sets a title label for the example
    */
    'label'?: string;
  }

  interface IntrinsicElements {
    'clio-button': ClioButton;
    'clio-checkbox': ClioCheckbox;
    'clio-combo-button': ClioComboButton;
    'clio-form': ClioForm;
    'clio-form-error': ClioFormError;
    'clio-icon': ClioIcon;
    'clio-input': ClioInput;
    'clio-label': ClioLabel;
    'clio-loader': ClioLoader;
    'clio-menu': ClioMenu;
    'clio-menu-item': ClioMenuItem;
    'clio-pill': ClioPill;
    'clio-popover': ClioPopover;
    'clio-radio': ClioRadio;
    'clio-radio-group': ClioRadioGroup;
    'clio-select': ClioSelect;
    'clio-textarea': ClioTextarea;
    'nova-example': NovaExample;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'clio-button': LocalJSX.ClioButton & JSXBase.HTMLAttributes<HTMLClioButtonElement>;
      'clio-checkbox': LocalJSX.ClioCheckbox & JSXBase.HTMLAttributes<HTMLClioCheckboxElement>;
      'clio-combo-button': LocalJSX.ClioComboButton & JSXBase.HTMLAttributes<HTMLClioComboButtonElement>;
      'clio-form': LocalJSX.ClioForm & JSXBase.HTMLAttributes<HTMLClioFormElement>;
      'clio-form-error': LocalJSX.ClioFormError & JSXBase.HTMLAttributes<HTMLClioFormErrorElement>;
      'clio-icon': LocalJSX.ClioIcon & JSXBase.HTMLAttributes<HTMLClioIconElement>;
      'clio-input': LocalJSX.ClioInput & JSXBase.HTMLAttributes<HTMLClioInputElement>;
      'clio-label': LocalJSX.ClioLabel & JSXBase.HTMLAttributes<HTMLClioLabelElement>;
      'clio-loader': LocalJSX.ClioLoader & JSXBase.HTMLAttributes<HTMLClioLoaderElement>;
      'clio-menu': LocalJSX.ClioMenu & JSXBase.HTMLAttributes<HTMLClioMenuElement>;
      'clio-menu-item': LocalJSX.ClioMenuItem & JSXBase.HTMLAttributes<HTMLClioMenuItemElement>;
      'clio-pill': LocalJSX.ClioPill & JSXBase.HTMLAttributes<HTMLClioPillElement>;
      'clio-popover': LocalJSX.ClioPopover & JSXBase.HTMLAttributes<HTMLClioPopoverElement>;
      'clio-radio': LocalJSX.ClioRadio & JSXBase.HTMLAttributes<HTMLClioRadioElement>;
      'clio-radio-group': LocalJSX.ClioRadioGroup & JSXBase.HTMLAttributes<HTMLClioRadioGroupElement>;
      'clio-select': LocalJSX.ClioSelect & JSXBase.HTMLAttributes<HTMLClioSelectElement>;
      'clio-textarea': LocalJSX.ClioTextarea & JSXBase.HTMLAttributes<HTMLClioTextareaElement>;
      'nova-example': LocalJSX.NovaExample & JSXBase.HTMLAttributes<HTMLNovaExampleElement>;
    }
  }
}


